// Word Bank for Imposter Game
// Each category contains an array of objects with 'w' (word) and 'h' (hint) properties

const wordBank = {
    "Regular": [
        {w: "Library", h: "Silence"}, {w: "Subway", h: "Underground"}, {w: "Umbrella", h: "Rain"},
        {w: "Backpack", h: "Straps"}, {w: "Mirror", h: "Reflection"}, {w: "Keyboard", h: "Input"},
        {w: "Compass", h: "Direction"}, {w: "Lantern", h: "Glow"}, {w: "Telescope", h: "Stars"},
        {w: "Hammock", h: "Swing"}, {w: "Briefcase", h: "Business"}, {w: "Stopwatch", h: "Timer"},
        {w: "Envelope", h: "Letter"}, {w: "Shovel", h: "Dig"}, {w: "Ladder", h: "Climb"},
        {w: "Curtain", h: "Window"}, {w: "Fountain", h: "Water"}, {w: "Calendar", h: "Dates"},
        {w: "Notebook", h: "Pages"}, {w: "Candle", h: "Flame"}, {w: "Whistle", h: "Blow"},
        {w: "Trophy", h: "Victory"}, {w: "Padlock", h: "Security"}, {w: "Scissors", h: "Cut"},
        {w: "Magnet", h: "Attract"}, {w: "Thermometer", h: "Temperature"}, {w: "Blanket", h: "Warmth"},
        {w: "Pillow", h: "Sleep"}, {w: "Bucket", h: "Carry"}, {w: "Wrench", h: "Tighten"},
        {w: "Drill", h: "Bore"}, {w: "Clipboard", h: "Notes"}, {w: "Stapler", h: "Bind"},
        {w: "Eraser", h: "Undo"}, {w: "Marker", h: "Highlight"}, {w: "Ruler", h: "Measure"},
        {w: "Globe", h: "Spin"}, {w: "Microscope", h: "Tiny"}, {w: "Calculator", h: "Numbers"},
        {w: "Projector", h: "Screen"}, {w: "Microphone", h: "Amplify"}, {w: "Speaker", h: "Sound"},
        {w: "Remote", h: "Channel"}, {w: "Battery", h: "Power"}, {w: "Charger", h: "Plug"},
        {w: "Cable", h: "Connect"}, {w: "Router", h: "Wireless"}, {w: "Monitor", h: "Display"},
        {w: "Printer", h: "Paper"}, {w: "Scanner", h: "Copy"}, {w: "Wallet", h: "Cards"},
        {w: "Passport", h: "Travel"}, {w: "Ticket", h: "Entry"}, {w: "Badge", h: "Identity"},
        {w: "Alarm", h: "Wake"}, {w: "Clock", h: "Tick"}, {w: "Sundial", h: "Shadow"},
        {w: "Compass", h: "North"}, {w: "Map", h: "Route"}, {w: "Blueprint", h: "Plan"},
        {w: "Scale", h: "Weight"}, {w: "Pulley", h: "Lift"}, {w: "Lever", h: "Force"},
        {w: "Gear", h: "Turn"}, {w: "Spring", h: "Coil"}, {w: "Hinge", h: "Swing"},
        {w: "Bolt", h: "Fasten"}, {w: "Nail", h: "Hammer"}, {w: "Screw", h: "Rotate"},
        {w: "Anchor", h: "Sea"}, {w: "Chain", h: "Link"}, {w: "Rope", h: "Knot"},
        {w: "Tape", h: "Stick"}, {w: "Glue", h: "Bond"}, {w: "Stamp", h: "Mail"},
        {w: "Coin", h: "Currency"}, {w: "Gem", h: "Sparkle"}, {w: "Ring", h: "Finger"},
        {w: "Necklace", h: "Chain"}, {w: "Bracelet", h: "Wrist"}, {w: "Crown", h: "Royal"},
        {w: "Helmet", h: "Protect"}, {w: "Shield", h: "Defense"}, {w: "Sword", h: "Blade"},
        {w: "Bow", h: "Arrow"}, {w: "Torch", h: "Fire"}, {w: "Tent", h: "Camp"},
        {w: "Sleeping Bag", h: "Outdoors"}, {w: "Canteen", h: "Hydrate"}, {w: "Binoculars", h: "Far"},
        {w: "Parachute", h: "Fall"}, {w: "Lifeboat", h: "Rescue"}, {w: "Surfboard", h: "Wave"},
        {w: "Kayak", h: "Paddle"}, {w: "Skateboard", h: "Grind"}, {w: "Bicycle", h: "Pedal"},
        {w: "Helmet", h: "Safety"}, {w: "Kite", h: "Wind"}, {w: "Yo-Yo", h: "String"},
        {w: "Puzzle", h: "Pieces"}, {w: "Dice", h: "Roll"}, {w: "Chess", h: "Strategy"},
        {w: "Dartboard", h: "Bullseye"}, {w: "Hourglass", h: "Sand"}
    ],
    "Food": [
        {w: "Pizza", h: "Dough"}, {w: "Sushi", h: "Vinegar"}, {w: "Taco", h: "Shell"},
        {w: "Burger", h: "Grill"}, {w: "Pasta", h: "Boil"}, {w: "Steak", h: "Medium"},
        {w: "Ramen", h: "Broth"}, {w: "Dumpling", h: "Fold"}, {w: "Croissant", h: "Flaky"},
        {w: "Waffle", h: "Grid"}, {w: "Pancake", h: "Stack"}, {w: "Omelette", h: "Eggs"},
        {w: "Burrito", h: "Wrap"}, {w: "Quesadilla", h: "Melt"}, {w: "Nachos", h: "Crunch"},
        {w: "Pho", h: "Vietnam"}, {w: "Pad Thai", h: "Noodles"}, {w: "Curry", h: "Spice"},
        {w: "Biryani", h: "Fragrant"}, {w: "Shawarma", h: "Rotisserie"}, {w: "Falafel", h: "Chickpea"},
        {w: "Hummus", h: "Dip"}, {w: "Paella", h: "Saffron"}, {w: "Risotto", h: "Creamy"},
        {w: "Lasagna", h: "Layers"}, {w: "Gyoza", h: "Pan-Fried"}, {w: "Tempura", h: "Batter"},
        {w: "Kimchi", h: "Ferment"}, {w: "Peking Duck", h: "Crispy"}, {w: "Poutine", h: "Gravy"},
        {w: "Clam Chowder", h: "Creamy"}, {w: "Tiramisu", h: "Espresso"}, {w: "Cheesecake", h: "Cream"},
        {w: "Brownie", h: "Fudge"}, {w: "Donut", h: "Glazed"}, {w: "Macaron", h: "Colorful"},
        {w: "Pretzel", h: "Twist"}, {w: "Bagel", h: "Hole"}, {w: "Focaccia", h: "Olive"},
        {w: "Naan", h: "Tandoor"}, {w: "Crepe", h: "Thin"}, {w: "Churro", h: "Cinnamon"},
        {w: "Empanada", h: "Stuffed"}, {w: "Pierogi", h: "Polish"}, {w: "Moussaka", h: "Greek"},
        {w: "Tagine", h: "Morocco"}, {w: "Jollof Rice", h: "African"}, {w: "Bibimbap", h: "Mixed"},
        {w: "Tom Yum", h: "Sour"}, {w: "Gazpacho", h: "Chilled"}, {w: "Minestrone", h: "Vegetables"},
        {w: "Bouillabaisse", h: "Seafood"}, {w: "Goulash", h: "Hungary"}, {w: "Schnitzel", h: "Breaded"},
        {w: "Fondue", h: "Dip"}, {w: "Quiche", h: "Tart"}, {w: "Soufflé", h: "Rise"},
        {w: "Crème Brûlée", h: "Torch"}, {w: "Gelato", h: "Italian"}, {w: "Sorbet", h: "Fruity"},
        {w: "Mochi", h: "Chewy"}, {w: "Baklava", h: "Honey"}, {w: "Ceviche", h: "Lime"},
        {w: "Fried Rice", h: "Wok"}, {w: "Spring Roll", h: "Crispy"}, {w: "Satay", h: "Skewer"},
        {w: "Congee", h: "Porridge"}, {w: "Bao Bun", h: "Steam"}, {w: "Hot Dog", h: "Mustard"},
        {w: "Corn Dog", h: "Stick"}, {w: "Lobster Roll", h: "New England"}, {w: "Fish Tacos", h: "Lime"},
        {w: "Smoked Salmon", h: "Cured"}, {w: "Eggs Benedict", h: "Hollandaise"},
        {w: "French Toast", h: "Brioche"}, {w: "Granola", h: "Oats"}, {w: "Acai Bowl", h: "Berry"},
        {w: "Smoothie", h: "Blend"}, {w: "Milkshake", h: "Thick"}, {w: "Bubble Tea", h: "Pearls"},
        {w: "Espresso", h: "Shot"}, {w: "Latte", h: "Foam"}, {w: "Matcha", h: "Green"},
        {w: "Chai", h: "Spiced"}, {w: "Lemonade", h: "Citrus"}, {w: "Mango Lassi", h: "Yogurt"},
        {w: "Poke Bowl", h: "Hawaii"}, {w: "Gyudon", h: "Beef Bowl"}, {w: "Shakshuka", h: "Eggs in Sauce"},
        {w: "Okonomiyaki", h: "Japanese Pancake"}, {w: "Takoyaki", h: "Octopus Ball"},
        {w: "Grilled Cheese", h: "Melted"}, {w: "Club Sandwich", h: "Triple Decker"},
        {w: "Caesar Salad", h: "Dressing"}, {w: "Guacamole", h: "Avocado"},
        {w: "Salsa", h: "Tomato"}, {w: "Tzatziki", h: "Cucumber"}, {w: "Pesto", h: "Basil"},
        {w: "Maple Syrup", h: "Canada"}, {w: "Hot Sauce", h: "Bottle"}
    ],
    "Celebrities": [
        {w: "Taylor Swift", h: "Eras"}, {w: "Tom Cruise", h: "Stunts"}, {w: "The Rock", h: "Muscle"},
        {w: "Beyonce", h: "Queen"}, {w: "Elon Musk", h: "Mars"}, {w: "Lionel Messi", h: "Pitch"},
        {w: "Cristiano Ronaldo", h: "Siuuu"}, {w: "LeBron James", h: "Lakers"},
        {w: "Eminem", h: "Rap God"}, {w: "Rihanna", h: "Umbrella"},
        {w: "Justin Bieber", h: "Baby"}, {w: "Ariana Grande", h: "Ponytail"},
        {w: "Kanye West", h: "Yeezus"}, {w: "Drake", h: "Toronto"},
        {w: "Nicki Minaj", h: "Barbz"}, {w: "Post Malone", h: "Tattoos"},
        {w: "Billie Eilish", h: "Whisper"}, {w: "Ed Sheeran", h: "Ginger"},
        {w: "Adele", h: "Rolling"}, {w: "Bruno Mars", h: "Uptown"},
        {w: "Lady Gaga", h: "Poker Face"}, {w: "Katy Perry", h: "Firework"},
        {w: "Selena Gomez", h: "Wizards"}, {w: "Zendaya", h: "Spider-Man"},
        {w: "Timothée Chalamet", h: "Wonka"}, {w: "Ryan Reynolds", h: "Deadpool"},
        {w: "Chris Hemsworth", h: "Thor"}, {w: "Robert Downey Jr", h: "Iron Man"},
        {w: "Scarlett Johansson", h: "Black Widow"}, {w: "Jennifer Lawrence", h: "Hunger Games"},
        {w: "Dwayne Johnson", h: "Jungle"}, {w: "Will Smith", h: "Fresh Prince"},
        {w: "Denzel Washington", h: "Training Day"}, {w: "Leonardo DiCaprio", h: "Titanic"},
        {w: "Brad Pitt", h: "Fight Club"}, {w: "Johnny Depp", h: "Sparrow"},
        {w: "Morgan Freeman", h: "Narrator"}, {w: "Samuel L Jackson", h: "Snakes"},
        {w: "Keanu Reeves", h: "Neo"}, {w: "Tom Holland", h: "Spidey"},
        {w: "Zac Efron", h: "Troy"}, {w: "Chris Pratt", h: "Star-Lord"},
        {w: "Gal Gadot", h: "Wonder"}, {w: "Margot Robbie", h: "Barbie"},
        {w: "Emma Watson", h: "Hermione"}, {w: "Natalie Portman", h: "Padme"},
        {w: "Cardi B", h: "Okurrr"}, {w: "Megan Thee Stallion", h: "Hot Girl"},
        {w: "Doja Cat", h: "Planet Her"}, {w: "Olivia Rodrigo", h: "Drivers Seat"},
        {w: "Harry Styles", h: "Watermelon"}, {w: "Zayn", h: "Pillowtalk"},
        {w: "Shawn Mendes", h: "Stitches"}, {w: "Charlie Puth", h: "Attention"},
        {w: "The Weeknd", h: "Blinding"}, {w: "Travis Scott", h: "Astro"},
        {w: "Kendrick Lamar", h: "Compton"}, {w: "J Cole", h: "Forest Hills"},
        {w: "Neymar Jr", h: "Dribble"}, {w: "Kylian Mbappe", h: "Sprint"},
        {w: "Erling Haaland", h: "Goals"}, {w: "Stephen Curry", h: "Three"},
        {w: "Kevin Durant", h: "Slim"}, {w: "Giannis", h: "Greek Freak"},
        {w: "Serena Williams", h: "Grand Slam"}, {w: "Roger Federer", h: "Baseline"},
        {w: "Rafael Nadal", h: "Clay"}, {w: "Novak Djokovic", h: "Serbian"},
        {w: "Tiger Woods", h: "Masters"}, {w: "Usain Bolt", h: "Lightning"},
        {w: "Michael Phelps", h: "Butterfly"}, {w: "Mike Tyson", h: "Bite"},
        {w: "Conor McGregor", h: "Notorious"}, {w: "Floyd Mayweather", h: "Money"},
        {w: "Kobe Bryant", h: "Mamba"}, {w: "Michael Jordan", h: "Air"},
        {w: "Shaquille ONeal", h: "Diesel"}, {w: "Tom Brady", h: "GOAT"},
        {w: "Lionel Richie", h: "Hello"}, {w: "Michael Jackson", h: "Moonwalk"},
        {w: "Elvis Presley", h: "Graceland"}, {w: "Freddie Mercury", h: "Bohemian"},
        {w: "David Bowie", h: "Ziggy"}, {w: "Bob Marley", h: "Reggae"},
        {w: "Jimi Hendrix", h: "Guitar God"}, {w: "Kurt Cobain", h: "Nirvana"},
        {w: "Tupac Shakur", h: "Thug Life"}, {w: "Notorious BIG", h: "Brooklyn"},
        {w: "Oprah Winfrey", h: "Giveaway"}, {w: "Steve Jobs", h: "Think Different"},
        {w: "Bill Gates", h: "Windows"}, {w: "Jeff Bezos", h: "Prime"},
        {w: "Mark Zuckerberg", h: "Social"}, {w: "Nikola Tesla", h: "Current"},
        {w: "Albert Einstein", h: "Relativity"}, {w: "Barack Obama", h: "Hope"},
        {w: "Kim Kardashian", h: "Reality"}, {w: "Paris Hilton", h: "Heiress"},
        {w: "Gordon Ramsay", h: "Hell's Kitchen"}, {w: "David Beckham", h: "Bend"}
    ],
    "Video Games": [
        {w: "Minecraft", h: "Blocks"}, {w: "Fortnite", h: "Building"}, {w: "Among Us", h: "Sus"},
        {w: "Valorant", h: "Abilities"}, {w: "Zelda", h: "Triforce"}, {w: "Mario Kart", h: "Shells"},
        {w: "Roblox", h: "Obby"}, {w: "Apex Legends", h: "Drop"}, {w: "Call of Duty", h: "Warzone"},
        {w: "Grand Theft Auto", h: "Open World"}, {w: "Red Dead Redemption", h: "Western"},
        {w: "The Last of Us", h: "Fungus"}, {w: "God of War", h: "Kratos"},
        {w: "Spider-Man", h: "Swing"}, {w: "Cyberpunk 2077", h: "Neon"},
        {w: "Elden Ring", h: "Souls"}, {w: "Dark Souls", h: "You Died"},
        {w: "Hollow Knight", h: "Bugs"}, {w: "Stardew Valley", h: "Farm"},
        {w: "Animal Crossing", h: "Island"}, {w: "Pokemon", h: "Catch"},
        {w: "Overwatch", h: "Hero"}, {w: "League of Legends", h: "Summoner"},
        {w: "Dota 2", h: "Radiant"}, {w: "Counter-Strike", h: "Bomb"},
        {w: "Battlefield", h: "Squad"}, {w: "Halo", h: "Spartan"},
        {w: "Destiny 2", h: "Guardian"}, {w: "Warframe", h: "Tenno"},
        {w: "Path of Exile", h: "Exile"}, {w: "Diablo IV", h: "Hell"},
        {w: "World of Warcraft", h: "Azeroth"}, {w: "Final Fantasy", h: "Crystal"},
        {w: "Kingdom Hearts", h: "Keyblade"}, {w: "Persona 5", h: "Phantom"},
        {w: "Monster Hunter", h: "Hunt"}, {w: "Tekken", h: "Mishima"},
        {w: "Street Fighter", h: "Hadouken"}, {w: "Mortal Kombat", h: "Fatality"},
        {w: "Super Smash Bros", h: "Stock"}, {w: "FIFA", h: "Kickoff"},
        {w: "NBA 2K", h: "MyCareer"}, {w: "Rocket League", h: "Boost"},
        {w: "Clash Royale", h: "Elixir"}, {w: "Clash of Clans", h: "Village"},
        {w: "Mobile Legends", h: "MOBA"}, {w: "Free Fire", h: "Booyah"},
        {w: "PUBG", h: "Chicken Dinner"}, {w: "Warzone", h: "Gulag"},
        {w: "Fall Guys", h: "Stumble"}, {w: "Lethal Company", h: "Quota"},
        {w: "Phasmophobia", h: "Ghost"}, {w: "Dead by Daylight", h: "Hook"},
        {w: "Five Nights at Freddy's", h: "Jumpscare"}, {w: "Subnautica", h: "Depths"},
        {w: "No Man's Sky", h: "Planets"}, {w: "Starfield", h: "Constellation"},
        {w: "Skyrim", h: "Dragonborn"}, {w: "Oblivion", h: "Tamriel"},
        {w: "Fallout 4", h: "Wasteland"}, {w: "Mass Effect", h: "Paragon"},
        {w: "Dragon Age", h: "Fade"}, {w: "The Witcher", h: "Geralt"},
        {w: "Assassin's Creed", h: "Creed"}, {w: "Watch Dogs", h: "Hack"},
        {w: "Far Cry", h: "Outpost"}, {w: "Ghost of Tsushima", h: "Samurai"},
        {w: "Sekiro", h: "Posture"}, {w: "Bloodborne", h: "Beast"},
        {w: "Cuphead", h: "Devil"}, {w: "Celeste", h: "Mountain"},
        {w: "Undertale", h: "Determination"}, {w: "Deltarune", h: "Knight"},
        {w: "Terraria", h: "Dig"}, {w: "Starcraft", h: "Zerg"},
        {w: "Age of Empires", h: "Villager"}, {w: "Civilization", h: "Turn"},
        {w: "SimCity", h: "Zones"}, {w: "The Sims", h: "Plumbob"},
        {w: "Cities Skylines", h: "Traffic"}, {w: "Planet Zoo", h: "Habitat"},
        {w: "Portal 2", h: "Science"}, {w: "Half-Life", h: "Crowbar"},
        {w: "Team Fortress 2", h: "Hats"}, {w: "Left 4 Dead", h: "Survivors"},
        {w: "BioShock", h: "Rapture"}, {w: "Dishonored", h: "Void"},
        {w: "Prey", h: "Mimics"}, {w: "Control", h: "Bureau"},
        {w: "Alan Wake", h: "Darkness"}, {w: "Death Stranding", h: "Connection"},
        {w: "Returnal", h: "Loop"}, {w: "Outer Wilds", h: "Supernova"},
        {w: "Disco Elysium", h: "Detective"}, {w: "Baldur's Gate 3", h: "Dice"},
        {w: "Lies of P", h: "Puppet"}, {w: "Armored Core", h: "Mech"}
    ],
    "Movies": [
        {w: "Inception", h: "Dreams"}, {w: "Titanic", h: "Iceberg"}, {w: "Star Wars", h: "Galaxy"},
        {w: "Harry Potter", h: "Wand"}, {w: "The Avengers", h: "Heroes"}, {w: "Joker", h: "Laugh"},
        {w: "Interstellar", h: "Wormhole"}, {w: "The Dark Knight", h: "Bat"},
        {w: "Oppenheimer", h: "Trinity"}, {w: "Barbie", h: "Pink"},
        {w: "Top Gun", h: "Maverick"}, {w: "Avatar", h: "Pandora"},
        {w: "Dune", h: "Spice"}, {w: "Parasite", h: "Basement"},
        {w: "Get Out", h: "Sunken"}, {w: "Us", h: "Scissors"},
        {w: "A Quiet Place", h: "Silence"}, {w: "Bird Box", h: "Blindfold"},
        {w: "Hereditary", h: "Grief"}, {w: "Midsommar", h: "Solstice"},
        {w: "The Shining", h: "Redrum"}, {w: "Psycho", h: "Shower"},
        {w: "Silence of the Lambs", h: "Chianti"}, {w: "Se7en", h: "Box"},
        {w: "Fight Club", h: "Soap"}, {w: "Pulp Fiction", h: "Briefcase"},
        {w: "Goodfellas", h: "Mob"}, {w: "The Godfather", h: "Offer"},
        {w: "Scarface", h: "Montana"}, {w: "Casino", h: "Vegas"},
        {w: "The Matrix", h: "Red Pill"}, {w: "John Wick", h: "Pencil"},
        {w: "Mad Max", h: "Fury Road"}, {w: "Edge of Tomorrow", h: "Loop"},
        {w: "Minority Report", h: "Precog"}, {w: "Total Recall", h: "Mars"},
        {w: "Blade Runner", h: "Replicant"}, {w: "2001 A Space Odyssey", h: "HAL"},
        {w: "Alien", h: "Xenomorph"}, {w: "Predator", h: "Jungle"},
        {w: "Terminator", h: "Judgment Day"}, {w: "RoboCop", h: "Prime"},
        {w: "Jurassic Park", h: "Raptor"}, {w: "Jumanji", h: "Jungle"},
        {w: "Home Alone", h: "Trap"}, {w: "Elf", h: "Cotton Balls"},
        {w: "The Lion King", h: "Pridelands"}, {w: "Toy Story", h: "Infinity"},
        {w: "Finding Nemo", h: "Coral"}, {w: "The Incredibles", h: "Cape"},
        {w: "Spirited Away", h: "Bathhouse"}, {w: "Princess Mononoke", h: "Forest"},
        {w: "Akira", h: "Neo-Tokyo"}, {w: "Your Name", h: "Comet"},
        {w: "Shutter Island", h: "Ward"}, {w: "The Prestige", h: "Pledge"},
        {w: "Memento", h: "Tattoo"}, {w: "Prisoners", h: "Maze"},
        {w: "Zodiac", h: "Cipher"}, {w: "Gone Girl", h: "Cool"},
        {w: "Black Swan", h: "Perfection"}, {w: "Whiplash", h: "Tempo"},
        {w: "La La Land", h: "Jazz"}, {w: "Birdman", h: "Ego"},
        {w: "Everything Everywhere", h: "Bagel"}, {w: "The Banshees", h: "Inisherin"},
        {w: "No Country for Old Men", h: "Coin Flip"}, {w: "There Will Be Blood", h: "Milkshake"},
        {w: "Requiem for a Dream", h: "Refrigerator"}, {w: "Black Mirror", h: "Screen"},
        {w: "Ready Player One", h: "Oasis"}, {w: "Tron", h: "Grid"},
        {w: "Wreck-It Ralph", h: "Arcade"}, {w: "Big Hero 6", h: "Baymax"},
        {w: "Moana", h: "Ocean"}, {w: "Encanto", h: "Casita"},
        {w: "Coco", h: "Marigold"}, {w: "Soul", h: "Jazz"},
        {w: "Turning Red", h: "Panda"}, {w: "Inside Out", h: "Emotions"},
        {w: "Up", h: "Balloons"}, {w: "WALL-E", h: "Trash"},
        {w: "Ratatouille", h: "Chef"}, {w: "Cars", h: "Piston Cup"},
        {w: "Brave", h: "Archery"}, {w: "Frozen", h: "Elsa"},
        {w: "Tangled", h: "Lantern"}, {w: "Maleficent", h: "Curse"},
        {w: "Doctor Strange", h: "Sanctum"}, {w: "Black Panther", h: "Vibranium"},
        {w: "Guardians of the Galaxy", h: "Mixtape"}, {w: "Thor Ragnarok", h: "Gladiator"},
        {w: "Endgame", h: "Snap"}, {w: "Spider-Man No Way Home", h: "Multiverse"},
        {w: "Wakanda Forever", h: "Tribute"}, {w: "Ant-Man", h: "Shrink"},
        {w: "Captain America", h: "Shield"}, {w: "Wonder Woman", h: "Lasso"},
        {w: "Aquaman", h: "Trident"}, {w: "The Batman", h: "Riddler"}
    ],
    "Countries & Cities": [
        {w: "Paris", h: "Eiffel"}, {w: "Tokyo", h: "Neon"}, {w: "Brazil", h: "Amazon"},
        {w: "Egypt", h: "Pyramids"}, {w: "Australia", h: "Kangaroo"}, {w: "Sweden", h: "Meatball"},
        {w: "Dubai", h: "Desert"}, {w: "New York", h: "Skyline"}, {w: "London", h: "Fog"},
        {w: "Rome", h: "Colosseum"}, {w: "Barcelona", h: "Gaudi"}, {w: "Amsterdam", h: "Canals"},
        {w: "Singapore", h: "Lion"}, {w: "Seoul", h: "Kimchi"}, {w: "Mumbai", h: "Bollywood"},
        {w: "Istanbul", h: "Bosphorus"}, {w: "Moscow", h: "Kremlin"}, {w: "Beijing", h: "Dragon"},
        {w: "Shanghai", h: "Bund"}, {w: "Hong Kong", h: "Harbor"},
        {w: "Bangkok", h: "Tuk Tuk"}, {w: "Bali", h: "Temple"},
        {w: "Maldives", h: "Overwater"}, {w: "Iceland", h: "Geyser"},
        {w: "Norway", h: "Fjord"}, {w: "Finland", h: "Aurora"},
        {w: "Switzerland", h: "Alps"}, {w: "Greece", h: "Parthenon"},
        {w: "Portugal", h: "Tiles"}, {w: "Morocco", h: "Medina"},
        {w: "Kenya", h: "Safari"}, {w: "South Africa", h: "Cape"},
        {w: "Nigeria", h: "Lagoon"}, {w: "Ethiopia", h: "Highlands"},
        {w: "Mexico", h: "Cactus"}, {w: "Argentina", h: "Pampas"},
        {w: "Peru", h: "Machu Picchu"}, {w: "Colombia", h: "Coffee"},
        {w: "Chile", h: "Atacama"}, {w: "Cuba", h: "Salsa"},
        {w: "Jamaica", h: "Reggae"}, {w: "Canada", h: "Maple"},
        {w: "Alaska", h: "Glaciers"}, {w: "Hawaii", h: "Volcano"},
        {w: "Los Angeles", h: "Hollywood"}, {w: "San Francisco", h: "Bridge"},
        {w: "Las Vegas", h: "Neon"}, {w: "Chicago", h: "Wind"},
        {w: "Miami", h: "Sunset"}, {w: "New Orleans", h: "Jazz"},
        {w: "India", h: "Spice"}, {w: "Pakistan", h: "Indus"},
        {w: "Bangladesh", h: "Delta"}, {w: "Sri Lanka", h: "Tea"},
        {w: "Nepal", h: "Everest"}, {w: "Tibet", h: "Dalai"},
        {w: "Mongolia", h: "Steppe"}, {w: "Kazakhstan", h: "Steppe"},
        {w: "Iran", h: "Persian"}, {w: "Iraq", h: "Mesopotamia"},
        {w: "Jordan", h: "Petra"}, {w: "Israel", h: "Wailing Wall"},
        {w: "Saudi Arabia", h: "Kaaba"}, {w: "Qatar", h: "World Cup"},
        {w: "Kuwait", h: "Gulf"}, {w: "Oman", h: "Incense"},
        {w: "Philippines", h: "Archipelago"}, {w: "Indonesia", h: "Spice Islands"},
        {w: "Malaysia", h: "Twin Towers"}, {w: "Vietnam", h: "Pho"},
        {w: "Cambodia", h: "Angkor"}, {w: "Myanmar", h: "Pagoda"},
        {w: "New Zealand", h: "Hobbit"}, {w: "Fiji", h: "Coral"},
        {w: "Madagascar", h: "Lemur"}, {w: "Tanzania", h: "Kilimanjaro"},
        {w: "Ghana", h: "Ashanti"}, {w: "Senegal", h: "Dakar"},
        {w: "Zimbabwe", h: "Victoria Falls"}, {w: "Zambia", h: "Copper"},
        {w: "Venezuela", h: "Angel Falls"}, {w: "Bolivia", h: "Saltflat"},
        {w: "Ecuador", h: "Galapagos"}, {w: "Uruguay", h: "Mate"},
        {w: "Paraguay", h: "Landlocked"}, {w: "Poland", h: "Pierogi"},
        {w: "Czech Republic", h: "Bohemian"}, {w: "Hungary", h: "Paprika"},
        {w: "Romania", h: "Dracula"}, {w: "Bulgaria", h: "Rakia"},
        {w: "Croatia", h: "Adriatic"}, {w: "Serbia", h: "Rakija"},
        {w: "Ukraine", h: "Sunflower"}, {w: "Belarus", h: "Bison"},
        {w: "Denmark", h: "Viking"}, {w: "Ireland", h: "Clover"},
        {w: "Scotland", h: "Bagpipe"}, {w: "Wales", h: "Dragon"}
    ],
    "Brands": [
        {w: "Nike", h: "Swoosh"}, {w: "Apple", h: "Bite"}, {w: "Tesla", h: "Electric"},
        {w: "McDonald's", h: "Fries"}, {w: "Coca-Cola", h: "Fizz"}, {w: "Google", h: "Search"},
        {w: "Adidas", h: "Stripes"}, {w: "Samsung", h: "Galaxy"}, {w: "Microsoft", h: "Window"},
        {w: "Amazon", h: "Smile"}, {w: "Meta", h: "Connect"}, {w: "Netflix", h: "Chill"},
        {w: "Spotify", h: "Stream"}, {w: "YouTube", h: "Subscribe"}, {w: "Twitter", h: "Bird"},
        {w: "Instagram", h: "Filter"}, {w: "TikTok", h: "FYP"}, {w: "Snapchat", h: "Ghost"},
        {w: "Discord", h: "Nitro"}, {w: "Reddit", h: "Upvote"},
        {w: "PlayStation", h: "Dualshock"}, {w: "Xbox", h: "Green"},
        {w: "Nintendo", h: "Mushroom"}, {w: "Steam", h: "Sales"},
        {w: "Nvidia", h: "Green Light"}, {w: "AMD", h: "Red"},
        {w: "Intel", h: "Core"}, {w: "ASUS", h: "Republic"}, {w: "Razer", h: "Snake"},
        {w: "Logitech", h: "Peripheral"}, {w: "Sony", h: "Walkman"},
        {w: "Bose", h: "Noise Cancel"}, {w: "Beats", h: "Dre"},
        {w: "JBL", h: "Boom"}, {w: "Sennheiser", h: "Audiophile"},
        {w: "Dyson", h: "Cyclone"}, {w: "LG", h: "Life's Good"},
        {w: "Panasonic", h: "Toughbook"}, {w: "Canon", h: "Lens"},
        {w: "Nikon", h: "DSLR"}, {w: "GoPro", h: "Action"},
        {w: "DJI", h: "Drone"}, {w: "Lego", h: "Brick"},
        {w: "Hasbro", h: "Monopoly"}, {w: "Mattel", h: "Barbie"},
        {w: "Ferrari", h: "Prancing"}, {w: "Lamborghini", h: "Bull"},
        {w: "Porsche", h: "911"}, {w: "BMW", h: "Kidney Grille"},
        {w: "Mercedes", h: "Star"}, {w: "Audi", h: "Rings"},
        {w: "Volkswagen", h: "Bug"}, {w: "Toyota", h: "Reliable"},
        {w: "Honda", h: "Civic"}, {w: "Ford", h: "Mustang"},
        {w: "Chevrolet", h: "Bow Tie"}, {w: "Jeep", h: "Off-Road"},
        {w: "Harley Davidson", h: "Hog"}, {w: "Rolex", h: "Oyster"},
        {w: "Gucci", h: "GG"}, {w: "Louis Vuitton", h: "Monogram"},
        {w: "Chanel", h: "No.5"}, {w: "Prada", h: "Nylon"},
        {w: "Versace", h: "Medusa"}, {w: "Balenciaga", h: "Triple S"},
        {w: "Supreme", h: "Box Logo"}, {w: "Off-White", h: "Quotation"},
        {w: "Yeezy", h: "Boost"}, {w: "Jordan", h: "Jumpman"},
        {w: "New Balance", h: "Numeric"}, {w: "Vans", h: "Checkerboard"},
        {w: "Converse", h: "Chuck"}, {w: "Puma", h: "Feline"},
        {w: "Reebok", h: "Classic"}, {w: "Under Armour", h: "Protect"},
        {w: "The North Face", h: "Summit"}, {w: "Patagonia", h: "Fleece"},
        {w: "IKEA", h: "Flat Pack"}, {w: "Zara", h: "Fast Fashion"},
        {w: "H&M", h: "Affordable"}, {w: "Uniqlo", h: "Basics"},
        {w: "Starbucks", h: "Mermaid"}, {w: "KFC", h: "Colonel"},
        {w: "Burger King", h: "Flame"}, {w: "Subway", h: "Footlong"},
        {w: "Domino's", h: "Delivery"}, {w: "Pizza Hut", h: "Pan"},
        {w: "Taco Bell", h: "Bell"}, {w: "Chipotle", h: "Burrito Bowl"},
        {w: "Dunkin", h: "Donut"}, {w: "Red Bull", h: "Wings"},
        {w: "Monster Energy", h: "Claw"}, {w: "Gatorade", h: "Electrolyte"},
        {w: "Pepsi", h: "Globe"}, {w: "Fanta", h: "Fruit"},
        {w: "Heineken", h: "Green Bottle"}, {w: "Marlboro", h: "Cowboy"}
    ]
};